export const COUNTER_TRADE = 'counterTrade'
export const COUNTER_TRADES = 'counterTrades'
export const ACCEPTED_COUNTER_TRADE = 'acceptedCounterTrade'
export const TRADE = 'trade'
export const TRADES = 'trades'
export const FAVORITES_TRADES = 'favoritesTrades'
export const VERIFIED_COLLECTIONS = 'verifiedCollections'
export const HEADER_ACTIONS = 'headerActions'
