export const COUNTER_TRADE = 'counterTrade'
export const COUNTER_TRADES = 'counterTrades'
export const ACCEPTED_COUNTER_TRADE = 'acceptedCounterTrade'
export const TRADE = 'trade'
export const ALL_TRADES = 'allTrades'
export const TRADES = 'trades'
export const ALL_LOANS = 'allLoans'
export const LOAN = 'loan'
export const LOANS = 'loans'
export const LOAN_OFFERS = 'loanOffers'
export const ACCEPTED_LOAN_OFFER = 'acceptedLoanOffer'
export const COUNTERED_TRADES = 'counteredTrades'

export const RAFFLE = 'raffle'
export const RAFFLES = 'raffles'
export const OUTGOING_RAFFLES = 'outgoingRaffles'
export const FAVORITES_RAFFLES = 'favoriteRaffles'
export const FAVORITES_TRADES = 'favoritesTrades'
export const FAVORITES_LOANS = 'favoritesLoans'
export const VERIFIED_COLLECTIONS = 'verifiedCollections'
export const NAME_SERVICE_REGISTERED_DOMAINS = 'nameServiceRegisteredDomains'
export const NAME_SERVICE_REGISTERED_DOMAIN_INFO = 'nameServiceRegisteredInfo'
export const HEADER_ACTIONS = 'headerActions'

export const TRADE_NOTIFICATIONS = 'tradeNotifications'
export const LOAN_NOTIFICATIONS = 'loanNotifications'

export const SEND_TRANSACTIONS = 'sendTransactions'
export const SEND_TRANSACTION = 'sendTransaction'
export const PARTIAL_WALLET_NFTS = 'partialWalletNFTs'
export const FULL_WALLET_NFTS = 'fullWalletNFTs'
export const SUPPORTED_CURRENCIES = 'supportedCurrencies'
export const LATEST_BLOCK = 'latestBlock'
export const AVERAGE_BLOCK_TIME = 'averageBlockTime'
